### ISSUE TITLE
relative paths should be relative to the database file

### ISSUE THREAD

**Issue by c-s-w** [marvinweber/KPSimpleBackup#30] opened 2020-10-28 22:59 UTC
Version 1.3

When using a relative path, it's converted to an absolute path based on the directory of the KeePass binary.

I'd expect it to be relative to the database file, as I want to save a copy next to the original file and not in the directory where KeePass is installed to.

**Comment by bugzc** [comment] 2021-01-01 22:58
I concur. I would expect backups to be tied to the original database path, rather than the software binary path.

**Comment by marvinweber** [comment] 2021-01-02 11:32
Thx for reporting this! I agree, too. It does make more sense to store backups relative to the database path rather than the application path.  

Caused by: #19

**Comment by marvinweber** [comment] 2021-04-06 18:55
This is fixed with the next [version 1.4](https://github.com/marvinweber/KPSimpleBackup/milestone/2).  
Realtive paths for backups will now always be resolved with the KeePass Database File as a Base/Start.

**Closed by marvinweber** 2021-04-06 18:55 UTC
Labels: bug

**Comment by SvenBent** [comment] 2022-03-22 13:51
v1.4. "Fixed" this issue but but created the reverse

I need the relative path to be according to the executable and not the database. MY database is on the gdrive and enabled Relative path here crashed ksimplebackup since its not able to handle the gdrive location.
I wish to keep a copy of the backups on my usb driver where keepass executable is on but unable to do so as the USB driver  letter might change, and relative paths no longer work according to the executable

Would it be possible to have a selecting for which relative "arnchor" to use ?

**Comment by marvinweber** [comment] 2022-04-11 11:06
@SvenBent, i see your point. I decided to "redesign" path selection in Version 2.0 (see #45); this will also enable what you want to do :)
